#
# Common code for all Loongson based systems
#

obj-$(CONFIG_MACH_LOONGSON) += common/

#
# Lemote Fuloong mini-PC (Loongson 2E-based)
#

obj-$(CONFIG_LEMOTE_FULOONG2E)  += fuloong-2e/

obj-$(CONFIG_LOONGSON_LS1A_BOARD)  += ls1a/
obj-$(CONFIG_LOONGSON_LS1B_BOARD)  += ls1b/
obj-$(CONFIG_LOONGSON_LS232_BOARD)  += ls232/
